### ISSUE TITLE
Message was not sent and threw an error

### ISSUE THREAD

**Issue by thelinuxlich** [clonn/slack-node-sdk#10]
/home/thelinuxlich/aidax_cron/node_modules/slack-node/lib/lib/slack.seed.js:58
        statusCode: body.statusCode,
                        ^
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/home/thelinuxlich/aidax_cron/node_modules/slack-node/lib/lib/slack.seed.js:58:25)
    at self.callback (/home/thelinuxlich/aidax_cron/node_modules/slack-node/node_modules/request/request.js:121:22)
    at Request.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/home/thelinuxlich/aidax_cron/node_modules/slack-node/node_modules/request/request.js:230:10)
    at ClientRequest.emit (events.js:95:17)
    at TLSSocket.socketErrorListener (_http_client.js:252:9)
    at TLSSocket.emit (events.js:117:20)
    at net.js:431:14
    at process._tickCallback (node.js:337:11)

**Comment by clonn** [comment]
@thelinuxlich  i execute ok, could you post code to gist???
