### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by m13** [clonn/slack-node-sdk#16]
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/home/ubuntu/worker_prod/node_modules/slack-node/lib/lib/slack.seed.js:97:28)
    at Request.self.callback (/home/ubuntu/worker_prod/node_modules/slack-node/node_modules/request/request.js:121:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/ubuntu/worker_prod/node_modules/slack-node/node_modules/request/request.js:978:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/ubuntu/worker_prod/node_modules/slack-node/node_modules/request/request.js:929:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

I cannot reproduce it, but it depends of the slack server. Maybe a connectivity problem, etc. but it should be handled somehow (check JSON.parse function)

**Comment by clonn** [comment]
now update https://www.npmjs.com/package/slack-node module, use tryrequest to replace request module. if any problem just tell me then.

thanks @m13
