### ISSUE TITLE
Error Handling: 414 Request-URI Too Long

### ISSUE THREAD

**Issue by brentchow** [clonn/slack-node-sdk#17]
When sending a request-URI too long for Slack's servers, a crash occurs and the following is logged:

````
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request.<anonymous> (/Users/JohnSmith/App/node_modules/slack-node/lib/lib/slack.seed.js:110:28)
    at Request.f (/Users/JohnSmith/App/node_modules/slack-node/node_modules/requestretry/node_modules/fg-lodash/node_modules/lodash/dist/lodash.js:5605:23)
    at Request.<anonymous> (/Users/JohnSmith/App/node_modules/slack-node/node_modules/requestretry/index.js:52:17)
    at Request.self.callback (/Users/JohnSmith/App/node_modules/slack-node/node_modules/requestretry/node_modules/request/request.js:368:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/Users/JohnSmith/App/node_modules/slack-node/node_modules/requestretry/node_modules/request/request.js:1219:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/JohnSmith/App/node_modules/slack-node/node_modules/requestretry/node_modules/request/request.js:1167:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
````

The JSON response attempting to be parsed at [./node_modules/slack-node/lib/lib/slack.seed.js:110:28](https://github.com/clonn/slack-node-sdk/blob/master/lib/lib/slack.seed.js#L109-111) is the following error page:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>414 Request-URI Too Large</title>
</head><body>
<h1>Request-URI Too Large</h1>
<p>The requested URL's length exceeds the capacity
limit for this server.<br />
</p>
</body></html>
````

**Comment by clonn** [comment]
@brentchow  do you have example url can let me try in test url?

thanks

**Comment by brentchow** [comment]
According to a Slack support agent -- thanks for your help, Tuan -- Slack has a "limit of 8k bytes".

I'm posting a `chat.message` with a large number of attachments. Occasionally the message I'm posting is approximately 8k or more bytes, resulting in the 414 error.

When logging `request_arg.form` at [./node_modules/slack-node/lib/lib/slack.seed.js:97](https://github.com/clonn/slack-node-sdk/blob/master/lib/lib/slack.seed.js#L97), it prints out the options for the post method to Slack. An example would be something along the lines of:

````
{ 
  username: 'Name of bot goes here',
  channel: '#########',
  text: 'Message goes here',
  icon_url: 'http://productslack.com/assets/img/ph/product-hunt-logo-80.png',
  attachments: '[
  {
    "fallback": "Et Lorem non excepteur exercitation mollit consequat ad ex veniam sit.",
    "title": "Trollery",
    "title_link": "http://www.example.com/",
    "text": "Officia occaecat aliqua Lorem fugiat sit labore commodo officia irure cillum nulla veniam.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Cupidatat consectetur ut et proident eu sint qui esse.",
    "title": "Eyewax",
    "title_link": "http://www.example.com/",
    "text": "Id incididunt id quis labore velit voluptate irure excepteur.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Esse deserunt non proident adipisicing cillum pariatur consectetur voluptate anim anim.",
    "title": "Eventex",
    "title_link": "http://www.example.com/",
    "text": "Et eu exercitation veniam laboris adipisicing.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Ex incididunt magna consequat adipisicing pariatur aliquip nisi aute tempor nisi.",
    "title": "Qimonk",
    "title_link": "http://www.example.com/",
    "text": "Deserunt Lorem dolor labore culpa excepteur pariatur laborum adipisicing.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Anim laborum elit sunt cupidatat Lorem aute sint veniam fugiat incididunt.",
    "title": "Temorak",
    "title_link": "http://www.example.com/",
    "text": "Nisi adipisicing enim amet deserunt do sint ipsum tempor anim consequat ipsum id commodo Lorem.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "In reprehenderit id voluptate eiusmod dolor excepteur aliqua cupidatat nostrud anim cillum fugiat consectetur.",
    "title": "Enormo",
    "title_link": "http://www.example.com/",
    "text": "Do id sint cupidatat velit occaecat adipisicing enim commodo.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Voluptate excepteur pariatur elit voluptate velit pariatur ea aute.",
    "title": "Isoternia",
    "title_link": "http://www.example.com/",
    "text": "Nulla magna dolore minim labore id.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Aliquip dolore ad excepteur elit ex quis nostrud eu ipsum sunt adipisicing.",
    "title": "Zaggle",
    "title_link": "http://www.example.com/",
    "text": "Quis laboris laborum nulla magna in fugiat velit est sit ad qui anim.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Eu ullamco magna sint dolor reprehenderit labore ullamco tempor.",
    "title": "Cincyr",
    "title_link": "http://www.example.com/",
    "text": "Labore do aute nisi irure deserunt fugiat.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Eu anim enim aute ullamco nisi nisi magna culpa velit ut mollit ea mollit.",
    "title": "Hawkster",
    "title_link": "http://www.example.com/",
    "text": "Tempor reprehenderit exercitation minim qui minim irure labore reprehenderit deserunt minim esse velit ad fugiat.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Non ea mollit magna amet aliquip amet pariatur laboris in irure sit.",
    "title": "Applideck",
    "title_link": "http://www.example.com/",
    "text": "Occaecat fugiat et amet anim amet culpa aute.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Occaecat ea duis elit labore excepteur ipsum cupidatat cillum ut non sint.",
    "title": "Geekular",
    "title_link": "http://www.example.com/",
    "text": "Commodo pariatur proident non aute eiusmod fugiat ut qui eu id velit pariatur.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Fugiat et eu laboris id culpa deserunt ipsum incididunt anim enim.",
    "title": "Telequiet",
    "title_link": "http://www.example.com/",
    "text": "Sunt irure cillum amet id incididunt eiusmod id nostrud elit consectetur ex.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Eiusmod commodo officia dolore quis enim ut aliqua laborum ipsum dolor dolore laboris minim cillum.",
    "title": "Zytrac",
    "title_link": "http://www.example.com/",
    "text": "Anim sunt non labore non sint sint id commodo sit.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Reprehenderit proident anim tempor sunt fugiat nisi sit magna velit cillum officia veniam consectetur.",
    "title": "Quordate",
    "title_link": "http://www.example.com/",
    "text": "Velit qui irure ut duis reprehenderit do ea aliqua.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Eiusmod duis duis ea exercitation.",
    "title": "Stelaecor",
    "title_link": "http://www.example.com/",
    "text": "Dolore sit culpa laborum id enim sunt.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Magna eiusmod pariatur dolore nostrud aliqua laboris labore aliqua excepteur pariatur.",
    "title": "Intergeek",
    "title_link": "http://www.example.com/",
    "text": "Reprehenderit ex minim consequat labore ea ipsum ipsum in in excepteur.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  },
  {
    "fallback": "Ipsum et nisi eu laboris proident duis fugiat ut.",
    "title": "Niquent",
    "title_link": "http://www.example.com/",
    "text": "Est ex esse aliquip dolore qui non.",
    "color": "#ffffff",
    "fields": [
      {
        "title": "Foo",
        "value": "Bar",
        "short": true
      },
      {
        "title": "XYZ",
        "value": "Benita",
        "short": true
      }
    ]
  }
]',
  token: 'xxxx-xxxxxxxxxx-xxxxxxxxxx-xxxxxxxxxx-xxxxxx'
}
````

**Comment by kevinburkeshyp** [comment]
Hey - guessing Slack has nginx or something sitting in front of their API and haven't configured an error handler. Just pushed a change recently to hit the callback with an error if the response can't be parsed as JSON, so this shouldn't crash anymore, hopefully: https://github.com/clonn/slack-node-sdk/blob/master/src/lib/slack.seed.coffee#L95
